//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOperation
    {
        public System.Guid RoleOperationID { get; set; }
        public int Id { get; set; }
        public int Operation { get; set; }
        public string Roles { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public Nullable<System.Guid> OperationID { get; set; }
    
        public virtual Operation Operation1 { get; set; }
    }
}
