//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.LoginHistories = new HashSet<LoginHistory>();
            this.UserLogs = new HashSet<UserLog>();
            this.Usersinroles = new HashSet<Usersinrole>();
        }
    
        public string USERNAME { get; set; }
        public string FullName { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Phone { get; set; }
        public string EMAIL { get; set; }
        public string PalmIP { get; set; }
        public string Address { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> LASTACTIVITYDATE { get; set; }
        public Nullable<System.DateTime> LASTLOGINDATE { get; set; }
        public Nullable<System.DateTime> LASTPASSWORDCHANGEDDATE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public string ISONLINE { get; set; }
        public bool ISLOCKEDOUT { get; set; }
        public Nullable<System.DateTime> LASTLOCKEDOUTDATE { get; set; }
        public Nullable<short> FAILEDPASSWORDATTEMPTCOUNT { get; set; }
        public Nullable<System.DateTime> FAILEDPASSWORDATTEMPTWS { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> SchoolId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginHistory> LoginHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usersinrole> Usersinroles { get; set; }
    }
}
