//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWRoleOperation
    {
        public string OperationName { get; set; }
        public int Operation { get; set; }
        public Nullable<System.Guid> OperationID { get; set; }
        public int Id { get; set; }
        public string ROLENAME { get; set; }
        public string Roles { get; set; }
        public string Description { get; set; }
        public string ModuleName { get; set; }
        public string OperationLink { get; set; }
        public string FullName { get; set; }
        public string USERNAME { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string CompanyName { get; set; }
        public System.Guid CompanyId { get; set; }
    }
}
