//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntiMoney_UMEntities : DbContext
    {
        public AntiMoney_UMEntities()
            : base("name=AntiMoney_UMEntities")
        {
            this.Database.CommandTimeout = 1800;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<LoginHistory> LoginHistories { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<RoleOperation> RoleOperations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SubSystem> SubSystems { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Usersinrole> Usersinroles { get; set; }
        public virtual DbSet<VWModule> VWModules { get; set; }
        public virtual DbSet<VWModuleSubsystem> VWModuleSubsystems { get; set; }
        public virtual DbSet<VWROLEOp> VWROLEOps { get; set; }
        public virtual DbSet<VWRoleOperationAssign> VWRoleOperationAssigns { get; set; }
        public virtual DbSet<VWRoleOperation> VWRoleOperations { get; set; }
    }
}
