//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntiLaunderingEntities : DbContext
    {
        public AntiLaunderingEntities()
            : base("name=AntiLaunderingEntities")
        {
            //this.Database.CommandTimeout = 1800;
            this.Database.CommandTimeout = 1048576;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackMarketRate> BlackMarketRates { get; set; }
        public virtual DbSet<RowData> RowDatas { get; set; }
        public virtual DbSet<FraudDetectedBlack> FraudDetectedBlacks { get; set; }
        public virtual DbSet<FraudDetectedBlackCount> FraudDetectedBlackCounts { get; set; }
        public virtual DbSet<FraudDetectedBlackCountFiltered> FraudDetectedBlackCountFiltereds { get; set; }
    }
}
