//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackMarketRate
    {
        public System.Guid BlackMarketRateID { get; set; }
        public string ExchangeName { get; set; }
        public string ExchangeCode { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public Nullable<decimal> RateAmountInBirr { get; set; }
        public Nullable<decimal> BankRate { get; set; }
        public string RecorderBy { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
    }
}
