//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public int NumberOfVehicles { get; set; }
        public string CompanyLogo { get; set; }
        public string Photo { get; set; }
        public string City { get; set; }
        public string SubCity { get; set; }
        public string Woreda { get; set; }
        public string POBOX { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string ManagerName { get; set; }
        public string Email { get; set; }
        public string Descrbition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
