//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.RoleOperations = new HashSet<RoleOperation>();
        }
    
        public System.Guid OperationID { get; set; }
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public int SubSystem { get; set; }
        public string OperationName { get; set; }
        public string OperationLink { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> SubSystemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleOperation> RoleOperations { get; set; }
        public virtual SubSystem SubSystem1 { get; set; }
    }
}
