//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usersinrole
    {
        public System.Guid UsersinrolesID { get; set; }
        public int Id { get; set; }
        public string USERNAME { get; set; }
        public string ROLENAME { get; set; }
        public string Description { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
