//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiLaundering.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWModuleSubsystem
    {
        public string SubSystemName { get; set; }
        public string ModuleName { get; set; }
        public string OperationName { get; set; }
        public string OperationLink { get; set; }
        public string Description { get; set; }
        public int Id { get; set; }
        public System.Guid OperationID { get; set; }
    }
}
